clc;
close all;
Am=input('Enter message signal amplitude: ');
Ac=input('Enter carrier signal amplitude: ');
fm=input('Enter message signal frequency: ');
fc=input('Enter carrier signal frequency: ');
t=0:0.00001:0.01;
mi=0.5;
Sm=Am*sin(2*pi*fm*t);
Sc=Ac*sin(2*pi*fc*t);
subplot(3,1,1);
plot(t,Sm);
title('Message signal');
ylabel('Amplitude');
xlabel('Time');
subplot(3,1,2);
plot(t,Sc);
title('Carrier signal');
ylabel('Amplitude');
xlabel('Time');
Sfm=Ac*sin(2*pi*fc*t+(mi*Sm));
subplot(3,1,3);
plot(t,Sfm);
title('FM Modulated signal');
ylabel('Amplitude');
xlabel('Time');
